export const GST_RATES = [
  { label: "Zero", value: 0 },
  { label: "Five", value: 5 },
  { label: "Twelve", value: 12 },
  { label: "Eighteen", value: 18 },
  { label: "Twenty Eight", value: 28 },
];

export const PAYMENT_MODES = [
  { value: "CASH", label: "Cash" },
  { value: "UPI", label: "UPI" },
  { value: "BANK_TRANSFER", label: "Bank Transfer" },
  { value: "CARD", label: "Card" },
];

export const STATES = [
  { key: "1", value: "Andhra Pradesh", label: "Andhra Pradesh" },
  { key: "2", value: "Arunachal Pradesh", label: "Arunachal Pradesh" },
  { key: "3", value: "Assam", label: "Assam" },
  { key: "4", value: "Bihar", label: "Bihar" },
  { key: "5", value: "Chandigarh", label: "Chandigarh" },
  { key: "6", value: "Chhattisgarh", label: "Chhattisgarh" },
  { key: "7", value: "Delhi", label: "Delhi" },
  { key: "8", value: "Goa", label: "Goa" },
  { key: "9", value: "Gujarat", label: "Gujarat" },
  { key: "10", value: "Haryana", label: "Haryana" },
  { key: "11", value: "Himachal Pradesh", label: "Himachal Pradesh" },
  { key: "12", value: "Jammu and Kashmir", label: "Jammu and Kashmir" },
  { key: "13", value: "Jharkhand", label: "Jharkhand" },
  { key: "14", value: "Karnataka", label: "Karnataka" },
  { key: "15", value: "Kerala", label: "Kerala" },
  { key: "16", value: "Ladakh", label: "Ladakh" },
  { key: "17", value: "Madhya Pradesh", label: "Madhya Pradesh" },
  { key: "18", value: "Maharashtra", label: "Maharashtra" },
  { key: "19", value: "Manipur", label: "Manipur" },
  { key: "20", value: "Meghalaya", label: "Meghalaya" },
  { key: "21", value: "Mizoram", label: "Mizoram" },
  { key: "22", value: "Nagaland", label: "Nagaland" },
  { key: "23", value: "Odisha", label: "Odisha" },
  { key: "24", value: "Puducherry", label: "Puducherry" },
  { key: "25", value: "Punjab", label: "Punjab" },
  { key: "26", value: "Rajasthan", label: "Rajasthan" },
  { key: "27", value: "Sikkim", label: "Sikkim" },
  { key: "28", value: "Tamil Nadu", label: "Tamil Nadu" },
  { key: "29", value: "Telangana", label: "Telangana" },
  { key: "30", value: "Tripura", label: "Tripura" },
  { key: "31", value: "Uttar Pradesh", label: "Uttar Pradesh" },
  { key: "32", value: "Uttarakhand", label: "Uttarakhand" },
  { key: "33", value: "West Bengal", label: "West Bengal" },
];
